mega squashed commit

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -28,7 +28,8 @@
     # icdiff = "!f() { git difftool --no-prompt --extcmd=\"icdiff $(git config --get icdiff.options)\" \"$@\" | less -R; }; f"
     # differ = "!f() { if which icdiff > /dev/null; then echo icdiff; else echo diff; fi; }; f"
 
-    main = "!f() { if git rev-parse --verify main >/dev/null 2>&1; then echo main; else echo master; fi; }; f"
+    # main = "!f() { git symbolic-ref refs/remotes/origin/HEAD | sed \"s@^refs/remotes/origin/@@\"; }; f"
+    main = "!f() { git remote show origin | sed -n '/HEAD branch/s/.*: //p'; }; f"
     delta = "!f() { git diff \"$@\" | delta -s; }; f"
     differ = "!f() { if which delta > /dev/null; then echo delta; else echo diff; fi; }; f"
 
@@ -64,6 +65,7 @@
     # bb = branch --show-current # works in newer version of git
     ba = branch -vv -a
     co = checkout
+    coo = "!f() { git fetch origin $@; git checkout $@; }; f"
     com = "!f() { git checkout $(git main) $@; }; f"
     cop = checkout -p
     new = checkout -b
@@ -116,9 +118,11 @@
     }; f"
     pu = "push -u"
     put = "push --tags"
+    pun = "push --no-verify"
     puf = "push -u --force-with-lease"
     pufn = "push -u --force-with-lease --no-verify"
     pufback = "!f() { local nback=${1:-1}; git puf origin HEAD~${nback}:$(git b --show-current); }; f"
+    puback = "!f() { local nback=${1:-1}; git pu origin HEAD~${nback}:$(git b --show-current); }; f"
     pl = "pull"
     plr = "pull --rebase"
     pla = "!f() { git pull; git submodule foreach git pull origin $(git main); }; f"
@@ -219,6 +223,20 @@
     hl = "!f() { hash=${1:-$(git rev-parse HEAD)}; hub browse -- commits/$hash; }; f"
     # hub show
     hs = "!f() { hash=${1:-$(git rev-parse HEAD)}; hub browse -- commit/$hash; }; f"
+
+    # does commit contain another (HEAD vs $1) or ($1 vs $2)
+    has = "!f() { \
+      if [[ $# -eq 1 ]]; then \
+        up=$1; down=HEAD; \
+      elif [[ $# -eq 2 ]]; then \
+        up=$2; down=$1; \
+      else echo \"⚠️  Usage: ghas <commit> OR ghas <commit1> <commit2>\"; \
+      fi; \
+      if $(git merge-base --is-ancestor $up $down); then \
+        echo \"✅ Yes, $down has $up\" && exit 0; \
+      else echo \"❌ No, $down does not have $up\" && exit 1; \
+      fi; \
+    }; f"
     issue = "!hub issue"
     fork = "!hub fork"
 
@@ -285,8 +303,9 @@
     dsm = "!f() { local mainbranch=$(git main); git --no-pager -c color.diff=always diff --stat $mainbranch;}; f"
     df = "!f() { git diff --name-only $@; }; f"
     mb = "!f() { echo $(git merge-base HEAD origin/$(git main)); }; f"
-    dfmb = "!f() { local merge_base=$(git mb); if [ $? -ne 0 ]; then echo "Error: Could not find merge base with origin/master"; return 1; fi; git diff --name-only $merge_base; }; f"
-    dsmb = "!f() { local merge_base=$(git mb); if [ $? -ne 0 ]; then echo "Error: Could not find merge base with origin/master"; return 1; fi; git diff --stat $merge_base; }; f"
+    dmb = "!f() { local merge_base=$(git mb); if [ $? -ne 0 ]; then echo "Error: Could not find merge base with origin/master"; return 1; fi; git diff $@ $merge_base; }; f"
+    dfmb = "!f() { git dmb --name-only; }; f"
+    dsmb = "!f() { git dmb --stat; }; f"
     dfom = "!f() { local mainbranch=$(git main); git diff --name-only origin/$mainbranch; }; f"
     dcf = "!f() { git diff --cached --name-only $@; }; f"
     dop = "!f() { $(git editor) $(git df); }; f"
@@ -297,7 +316,7 @@
     du = "!git $(git differ) @{upstream}"
 
     # status
-    s = "!f() { if [ -n \"$GIT_PREFIX\" ]; then cd \"$GIT_PREFIX\"; fi; git chain 'status' $@; }; f"
+    s = "!f() { if [ -n \"$GIT_PREFIX\" ]; then cd \"$GIT_PREFIX\"; fi; git chain 'status --short' $@; }; f"
     sh = show
     sho = "!f(){ local branch=$(git bb); git show origin/$branch $@; }; f"
     shom = "!f() { local mainbranch=$(git main); git show origin/$mainbranch; }; f"
@@ -308,7 +327,17 @@
 
 
     # tree
-    l = log --color --graph --pretty='%C(yellow)%h%C(reset) %Cred%cd%C(reset) %C(bold blue)%an%C(reset) %s%C(bold yellow)%d%C(reset)' --decorate --date=relative
+    l = "!f() { \
+        if [ $# -eq 0 ]; then \
+            if [ \"$(git bb)\" == \"$(git main)\" ]; then \
+                git log --graph --color --pretty='%C(yellow)%h%C(reset) %Cred%cd%C(reset) %C(bold blue)%an%C(reset) %s%C(bold yellow)%d%C(reset)' --decorate --date=relative $@; \
+            else \
+                git --no-pager log --graph --color --pretty='%C(yellow)%h%C(reset) %Cred%cd%C(reset) %C(bold blue)%an%C(reset) %s%C(bold yellow)%d%C(reset)' --decorate --date=relative $(git mb)~1..HEAD $@; \
+            fi \
+        else \
+            git log --graph --color --pretty='%C(yellow)%h%C(reset) %Cred%cd%C(reset) %C(bold blue)%an%C(reset) %s%C(bold yellow)%d%C(reset)' --decorate --date=relative $@; \
+        fi \
+    }; f"
     ls = log --color --pretty=format:'%C(yellow)%h%C(reset) %Cred%cd%C(reset) %C(bold blue)%an%C(reset) %s%C(bold yellow)%d%C(reset)' --decorate --date=relative --numstat
     lo = "!f(){ local branch=$(git bb); git log origin/$branch $@; }; f"
     lom = "!f() { local mainbranch=$(git main); git log origin/$mainbranch; }; f"
@@ -414,15 +443,16 @@
     # get branch
     # consider: g branch -a --format '%(refname); \
     zb = "!f() { \
-      local branch=$(git branch -a --sort=-committerdate | grep -v 'remotes/' | fzf -m --preview 'git l {1}'); \
+      local branch=$(git b | sed 's/^* //; s/^  //'  | grep -v 'remotes/' | fzf --tac -m --preview 'git l {1}' | awk '{ print $1 }'); \
       if [[ -z $branch ]]; then return 1; fi; \
       echo \"$branch\"; \
     }; f"
     zba = "!f() { \
-      local branch=$(git branch -a --sort=-committerdate | fzf -m --preview 'git l {1}'); \
+      local branch=$(git b -a | sed 's/^* //; s/^  //'  | fzf --tac -m --preview 'git l {1}' | awk '{ print $1 }'); \
       if [[ -z $branch ]]; then return 1; fi; \
       echo \"$branch\"; \
     }; f"
+    zbx = "!f() { local branch=$(git zb); if [[ -z $branch ]]; then return 1; fi; git bx $branch; }; f"
     # fuzzy open
     zop = "!f() { \
       local file=$(git zf); \
